{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runner-coordinator.fullname" . }}
  labels:
    {{- include "runner-coordinator.labels" . | nindent 4 }}
type: Opaque
stringData:
  GITLAB_TOKEN: {{ .Values.gitlabToken | quote }}
  GITLAB_RUNNER_REGISTRATION_TOKEN: {{ .Values.runnerRegistrationToken | quote }}
{{- end }}
